version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 3333:3333
    container_name: api

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: web

  database:
    image: mysql:8
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3006:3006
    volumes:
      - ./backend/src/shared/infra/database/mysql-seeder:/docker-entrypoint-initdb.d
